using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace HelloGen;

[Generator(LanguageNames.CSharp)]
public class ComponentGenerator : IIncrementalGenerator
{
    private const string ComponentAttributeName = "HelloLib.ComponentAttribute";
    private const string DefaultAttributeName = "HelloLib.DefaultAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext initContext)
    {
        var componentClasses = initContext.SyntaxProvider
            .ForAttributeWithMetadataName(
                ComponentAttributeName,
                static (syntaxNode, _) => syntaxNode is ClassDeclarationSyntax,
                static (syntaxContext, _) => Transform(syntaxContext))
            .Where(static x => x is not null);

        var grouped = componentClasses.Collect();

        initContext.RegisterSourceOutput(grouped,
            static (spc, arr) =>
            {
                foreach (var rawInfo in arr)
                {
                    if (rawInfo is null) continue;
                    var info = (ComponentTypeInfo)rawInfo;
                    var source = GenerateForType(info);
                    var fileName = $"{info.TypeName}.g.cs";
                    spc.AddSource(fileName, SourceText.From(source, Encoding.UTF8));
                }
            });
    }

    private static ComponentTypeInfo? Transform(GeneratorAttributeSyntaxContext ctx)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.TargetNode;
        var typeSym = (INamedTypeSymbol)ctx.TargetSymbol;

        var ns = typeSym.ContainingNamespace;
        var namespaceName =
            ns.IsGlobalNamespace ? "" : ns.ToDisplayString();

        var userUsings = classDecl.SyntaxTree.GetRoot()
            .DescendantNodes()
            .OfType<UsingDirectiveSyntax>()
            .Select<UsingDirectiveSyntax, string>(u => u.ToFullString())
            .ToImmutableHashSet(StringComparer.Ordinal);
        
        var properties = typeSym.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(x => x.DeclaredAccessibility == Accessibility.Public &&
                        x.GetMethod is not null &&
                        x.SetMethod is not null)
            .Select(x => new PropertyInfo(
                Name: x.Name,
                Type: x.Type,
                HasDefault: x.GetAttributes()
                    .Any(a => DefaultAttributeName.Equals(a.AttributeClass?.ToDisplayString())),
                DefaultValue: GetValue(x.GetAttributes()),
                FieldName: $"_{char.ToLowerInvariant(x.Name[0])}{x.Name.Substring(1, x.Name.Length - 1)}")).ToImmutableArray();

        return new ComponentTypeInfo(
            Namespace: namespaceName,
            TypeName: typeSym.Name,
            Properties: properties,
            UserUsings: userUsings);
    }

    private static object? GetValue(ImmutableArray<AttributeData> attrs)
    {
        const string NamedArgumentKey = "Value";
        return attrs.Where(attr => DefaultAttributeName.Equals(attr.AttributeClass?.ToDisplayString()))
            .Select(attr => attr.NamedArguments.FirstOrDefault())
            .Where(kvp => kvp.Key == NamedArgumentKey)
            .Select(kvp => kvp.Value.Value)
            .FirstOrDefault();
    }

    private static string GenerateForType(ComponentTypeInfo info)
    {
        var @namespace = string.IsNullOrWhiteSpace(info.Namespace) ?
                string.Empty : $"namespace {info.Namespace};";
        var usings = GenerateUsings(info);

        var fields = string.Join("\n\n", info.Properties.Select(GenerateField));
        var methods = string.Join("\n\n", info.Properties.Select(GenerateMethod));
        var events = string.Join("\n\n", info.Properties.Select(GenerateEvents));

        return $$"""
                 //<auto-generated/>
                 {{usings}}

                 {{@namespace}}

                 public partial class {{info.TypeName}}
                 {
                    {{fields}}
                 
                    {{methods}}
                 
                    {{events}}
                 }
                 """;
    }
    
    private static string GenerateUsings(ComponentTypeInfo info)
    {
        var required = new HashSet<string>(StringComparer.Ordinal) { "using System;" };

        var all = info.UserUsings
            .Concat(required)
            .Distinct(StringComparer.Ordinal)
            .ToArray();
        
        return string.Join("\n", all);
    }

    private static string GenerateField(PropertyInfo p)
    {
        var init = p.HasDefault ? $"= {FormatLiteral(p.DefaultValue)}" : string.Empty;
        return $@"private {p.Type.ToDisplayString()} {p.FieldName} {init};";
    }

    private static string GenerateMethod(PropertyInfo p)
    {
        var getterBody = $"public {p.Type.ToDisplayString()} Get{p.Name}() => {p.FieldName};";
        var setterBody = $$"""
                          public void Set{{p.Name}}({{p.Type.ToDisplayString()}} value){
                            {{p.Name}}Changing?.Invoke(value);
                            if (Equals(value,{{p.FieldName}})) return;
                            {{p.FieldName}} = value;
                            {{p.Name}}Changed?.Invoke(value);
                          }
                          """;
        return $"""
                {getterBody}
                {setterBody}
                """;
    }

    private static string GenerateEvents(PropertyInfo p) =>
        $"""
         public event Action<{p.Type.ToDisplayString()}> {p.Name}Changing;
         public event Action<{p.Type.ToDisplayString()}> {p.Name}Changed;
         """;

    private static string FormatLiteral(object? value)
    {
        return value switch
        {
            string s => $"\"{s.Replace("\"", "\\\"")}\"",
            char c => $"'{c}'",
            byte b => $"{b}",
            short s => $"{s}",
            int i => $"{i}",
            long l => $"{l}L",
            float f => $"{f}f",
            double d => d.ToString(CultureInfo.InvariantCulture) + "d",
            decimal dm => dm.ToString(CultureInfo.InvariantCulture) + "m",
            bool b => b ? "true" : "false",
            null => "null",
            INamedTypeSymbol { TypeKind: TypeKind.Enum } =>
                SyntaxFactory.LiteralExpression(SyntaxKind.StringLiteralExpression,
                    SyntaxFactory.Literal(value.ToString() ?? "0")).ToFullString(),
            _ => SyntaxFactory.LiteralExpression(SyntaxKind.StringLiteralExpression,
                SyntaxFactory.Literal(
                value.ToString())).ToFullString()
        };
    }
}

internal record struct ComponentTypeInfo(
    string? Namespace,
    string TypeName,
    ImmutableArray<PropertyInfo> Properties,
    ImmutableHashSet<string> UserUsings);

internal record struct PropertyInfo(
    string Name,
    ITypeSymbol Type,
    bool HasDefault,
    object? DefaultValue,
    string FieldName);