<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <LangVersion>preview</LangVersion>
        <Nullable>enable</Nullable>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <NoWarn>$(NoWarn);RS2008</NoWarn>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Authors>Cremis018</Authors>
        <Company>DeadDog</Company>
        <Description>测试包管理工具的项目</Description>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <IsRoslynComponent>true</IsRoslynComponent>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <OutputPath>C:\MyNuget\Debug</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <OutputPath>C:\MyNuget\Release</OutputPath>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" PrivateAssets="all" />
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="4.14.0" PrivateAssets="all">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <None Include="$(OutputPath)\$(AssemblyName).dll" 
              Pack="true" 
              PackagePath="analyzers/dotnet/cs" 
              Visible="false" />
    </ItemGroup>

    <Target Name="GetDependencyTargetPaths" AfterTargets="ResolvePackageDependenciesForBuild">
        <ItemGroup>
            <TargetPathWithTargetPlatformMoniker Include="@(ResolvedCompileFileDefinitions)" IncludeRuntimeDependency="false" />
        </ItemGroup>
    </Target>
    
</Project>
