<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Authors>Cremis018</Authors>
        <Description>包管理工具测试项目</Description>
        <Company>DeadDog</Company>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <LangVersion>10</LangVersion>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <OutputPath>C:\MyNuget\Debug</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <OutputPath>C:\MyNuget\Release</OutputPath>
    </PropertyGroup>

    <ItemGroup> 
        <None Include="..\GeneratorDemo\bin\$(Configuration)\netstandard2.1\GeneratorDemo.dll"
              PackgePath="analyzers/dotnet/cs"
              Pack="true"
              Visible="false" />
        <Content Remove="$(OutputPath)\$(AssemblyName).dll" />
    </ItemGroup>
</Project>
